name: pytest

on:
  push:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Pytest
        run: pip install pytest

      - name: Run Pytest
        run: python -m pytest src/tests -v
